version: '2'
services:
  memcached:
    image: memcached:1.4
    ports:
      - "11212:11211"

  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql

  mysql:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: 9hj3608jbg
      MYSQL_DATABASE: steve_v1
      MYSQL_USER: steve_v1
      MYSQL_PASSWORD: 9hj3608jbg
    ports:
      - "13306:3306"
    volumes_from:
      - data
    volumes:
      - ../../repo/db.sql.gz:/docker-entrypoint-initdb.d/db.sql.gz
    container_name: mysql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../repo/:/var/www/html
    links:
      - web
    container_name: nginx

  web:
    #    build: ./php-fpm73   # <- if you want to use PHP7.3
    #    build: ./php-fpm72   # <- if you want to use PHP7.2
    build: ./php-fpm71
    #    build: ./php-fpm56    # <- if you want to use PHP5.6
    volumes:
      - ../../repo/:/var/www/html
    links:
      - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'steve_v1'
      DATABASE_USER: 'steve_v1'
      DATABASE_PASSWORD: '9hj3608jbg'
    container_name: web

  cron:
    #    build: ./php-fpm73   # <- if you want to use PHP7.3
    #    build: ./php-fpm72   # <- if you want to use PHP7.2
    build: ./php-fpm71
    #    build: ./php-fpm56    # <- if you want to use PHP5.6
    volumes:
      - ../../repo/:/var/www/html
    command: start-cron
    environment:
      CRONTAB_CONTENT: |
        * * * * * cd /var/www/html/store && php html/index.php croncontrol/emails
        * * * * * cd /var/www/html/store && php html/index.php croncontrol/feeds
        15 * * * * cd /var/www/html/store && php html/index.php croncontrol/hourly
        0 2 * * * cd /var/www/html/store && php html/index.php croncontrol/daily
        0 22 * * 6 cd /var/www/html/store && php html/index.php croncontrol/weeklys
        0 0 1 * * cd /var/www/html/store && php html/index.php croncontrol/monthly
        * * * * * cd /var/www/html/store && php html/index.php croncontrol/processparts

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - '8080:80'
    links:
        - mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: 9hj3608jbg
        PMA_HOST: mysql
